### ISSUE TITLE
用不了呀，404not found

### ISSUE THREAD

**Issue by myzeling** [cgisky1980/ai00_rwkv_server#12]
![9)O4P4F%YET%CQFGU)C){~X](https://github.com/cgisky1980/ai00_rwkv_server/assets/126534758/36270ab6-f8ca-4837-a2d8-4aa51196a4b5)
![9)O4P4F%YET%CQFGU)C){~X](https://github.com/cgisky1980/ai00_rwkv_server/assets/126534758/2ccda210-6e3a-4962-a186-d9a92c169420)
就一直这样，根本没法用
![image](https://github.com/cgisky1980/ai00_rwkv_server/assets/126534758/b7ac1b27-831b-4642-9d3c-a5eef4289c6e)

**Comment by myzeling** [comment]
![image](https://github.com/cgisky1980/ai00_rwkv_server/assets/126534758/fece41df-4592-4bb0-bb15-735bf793db10)

**Comment by taixs** [comment]
点对话和论文，都没法使用。
信息如下：

D:\Developer\Ai\ai00_server> ./ai00_server.exe --model RWKV-4-World-CHNtuned-7B-v1-20230709-ctx4096.st

2023-07-26T02:24:11.408Z INFO  [ai00_server] server started at http://0.0.0.0:3000
2023-07-26T02:24:29.854Z INFO  [ai00_server] AdapterInfo {
    name: "NVIDIA GeForce RTX 2060 SUPER",
    vendor: 4318,
    device: 7942,
    device_type: DiscreteGpu,
    driver: "NVIDIA",
    driver_info: "536.40",
    backend: Vulkan,
}
2023-07-26T02:24:29.854Z INFO  [ai00_server] ModelInfo {
    num_layers: 32,
    num_emb: 4096,
    num_vocab: 65536,
}
2023-07-26T02:25:08.867Z TRACE [ai00_server] Sampler {
    top_p: 0.5,
    temperature: 1.2,
    presence_penalty: 0.4,
    frequency_penalty: 0.4,
}
2023-07-26T02:25:08.868Z TRACE [ai00_server] state cache miss
2023-07-26T02:25:08.868Z TRACE [ai00_server] Assistant: 你好，我是你的AI助手。有什么问题或指令请尽管吩咐！


User: 你好啊。

Assistant:
thread '<unnamed>' panicked at 'Error in Queue::submit: Validation Error

Caused by:
    Parent device is lost
', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.16.3\src\backend\direct.rs:2252:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by cgisky1980** [comment]
给一下GPU型号，以及内存大小    估计是内存爆了    试试3B的模型  7B可以等量化工作完成

**Comment by cgisky1980** [comment]
>@taixs 给一下GPU型号，以及内存大小 估计是内存爆了 试试3B的模型 7B可以等量化工作完成

**Comment by cgisky1980** [comment]
> ![9)O4P4F%YET%CQFGU)C){~X](https://user-images.githubusercontent.com/126534758/256088843-36270ab6-f8ca-4837-a2d8-4aa51196a4b5.png) ![9)O4P4F%YET%CQFGU)C){~X](https://user-images.githubusercontent.com/126534758/256088986-2ccda210-6e3a-4962-a186-d9a92c169420.png) 就一直这样，根本没法用 ![image](https://user-images.githubusercontent.com/126534758/256089070-b7ac1b27-831b-4642-9d3c-a5eef4289c6e.png)

额  点右边菜单。。。不过已经更新webUI了  git pull 一下再试试

**Comment by cgisky1980** [comment]
@myzeling  贴一下命令行的信息  还有 GPU 等等的信息

**Comment by cryscan** [comment]
@taixs RTX 2060专用显存太少，运行不了7B模型。

**Comment by myzeling** [comment]
> @myzeling 贴一下命令行的信息 还有 GPU 等等的信息
命令行就是上面的，没有其他的，gpu是核显。

**Comment by taixs** [comment]
> > @taixs   估计是内存爆了 试试3B的模型 7B可以等量化工作完成

OK，感谢回答，我试试其他模型。
